config/routes.rb
TestApp::Application.routes.draw do
 
get 'snames/search', :as => :search

 resources :snames do 
 collection { post :import }
 
end

   root :to => 'snames#index'

end

app/models/sname.rb
class Sname < ActiveRecord::Base
  attr_accessible :name ,:rank, :count, :prop100k, :cum_prop100k, :pctwhite, :pctblack, :pctapi, :pctaian, :pct2prace, :pcthispanic

#method that is importing the csv file to the table  
def self.import(file) 
  CSV.foreach(file.path, :headers => true) do |row|
  Sname.create!(row.to_hash)
  end
end

def self.search(search)

  if search 
    where("name  REGEXP?",  "[a-z]"+"#{search}""|" "^"+"#{search}"+"$" )
  # this is the REGUlar expression  that searchs the post string 
  #else
  # find(:all)

  end
 

end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/imports_controller.rb
require 'csv'

class ImportsController < ApplicationController

 def new
    @import = Import.new
    end
    def create
    @import = Import.new(params[:import])
    respond_to do |format|
      if @import.save!
        flash[:notice] = 'CSV data was successfully imported.'
        format.html { redirect_to(@import) }
      else
        flash[:error] = 'CSV data import failed.'
        format.html { render :action => "new" }
      end
    end
    end
    def show
    @import = Import.find(params[:id])
    end
    def proc_csv
    @import = Import.find(params[:id])
    lines = parse_csv_file(@import.csv.path)
    lines.shift #comment this line out if your CSV file doesn't contain a header row
    if lines.size >
      @import.processed = lines.size
      lines.each do |line|
        case @import.datatype
        when "releases"
          new_release(line)
        end
      end
      @import.save
      flash[:notice] = "CSV data processing was successful."
      redirect_to :action => "show", :id => @import.id
    else
      flash[:error] = "CSV data processing failed."
      render :action => "show", :id => @import.id
    end
    end
private
  def parse_csv_file(path_to_csv)
    lines = []
    #if not installed run, sudo gem install fastercsv
    #http://fastercsv.rubyforge.org/
    require 'fastercsv'
    FasterCSV.foreach(path_to_csv) do |row|
      lines << row
    end
    lines
  end
    def new_release(line)
    params = Hash.new
    params[:release] = Hash.new
    params[:release]["title"] = line[0]
        params[:release]["rdate"] = line[1]
    params[:release]["body"] = line[3]
    params[:release]["notes"] = line[4]
    release = Release.new(params[:release])
    release.save
    end



end

app/controllers/snames_controller.rb
require 'csv'
#this is the scaffold names snames 
class SnamesController < ApplicationController

  # GET /snames
  # GET /snames.json
  def index
    
    @snames = Sname.search(params[:search])
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snames }
     end
  end

  # GET /snames/1
  # GET /snames/1.json
  def show
    @sname = Sname.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sname }
    end
  end

  # GET /snames/new
  # GET /snames/new.json
  def new
    @sname = Sname.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sname }
    end
  end

  # GET /snames/1/edit
  def edit
    @sname = Sname.find(params[:id])
  end

  # POST /snames
  # POST /snames.json
  def create
    @sname = Sname.new(params[:sname])

    respond_to do |format|
      if @sname.save
        format.html { redirect_to @sname, notice: 'Sname was successfully created.' }
        format.json { render json: @sname, status: :created, location: @sname }
      else
        format.html { render action: "new" }
        format.json { render json: @sname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snames/1
  # PUT /snames/1.json
  def update
    @sname = Sname.find(params[:id])

    respond_to do |format|
      if @sname.update_attributes(params[:sname])
        format.html { redirect_to @sname, notice: 'Sname was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snames/1
  # DELETE /snames/1.json
  def destroy
    @sname = Sname.find(params[:id])
    @sname.destroy

    respond_to do |format|
      format.html { redirect_to snames_url }
      format.json { head :no_content }
    end
  end



#method use to import csv file 

def import
  Sname.import(params[:file])
  redirect_to root_url, notice: "Products imported."
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/snames_helper.rb
module SnamesHelper
end

app/views/imports/show.html.erb
<%= @import.csv.path %>

<% if @import.processed > 0 %>

Success! This import contained <%=  @import.processed %> records

<% else %>

<%= link_to "process", import_path(@import.id) %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <div id="search">

  </div>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snames/_form.html.erb
<%= form_for(@sname) do |f| %>
  <% if @sname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sname.errors.count, "error") %> prohibited this sname from being saved:</h2>

      <ul>
      <% @sname.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snames/_import.html.erb
<%= form_tag import_snames_path, multipart: true %>
<%= file_field_tag :file %>
<%= submit_tag "import" %>

app/views/snames/_search.html.erb
  <%= form_tag snames_path, :method => 'get' do %>

      <%= text_field_tag :search, params[:search], :id => 'search_field' %>
      <%= submit_tag "Search", :name => nil %> 
      <%= link_to_function "Clear", "$('search_field').clear()" %>
  <% end %> 

app/views/snames/edit.html.erb
<h1>Editing sname</h1>

<%= render 'form' %>

<%= link_to 'Show', @sname %> |
<%= link_to 'Back', snames_path %>

app/views/snames/index.html.erb
 
<% if @snames.nil?  %>
<%= link_to "welcome to the search" , root_url %> <br />
<%= render :partial => 'snames/search' %>
<% else %>
<%= link_to "welcome to the search" , root_url %> <br />
<h1>Listing Names</h1> <br />
<%= @snames.count  %> results founds 

<table>

  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>





<% @snames.each do |sname| %>

  <tr>
    <td><%= sname.name %></td>
    <td><%= link_to 'Show', sname %></td>
    <td><%= link_to 'Edit', edit_sname_path(sname) %></td>
    <td><%= link_to 'Destroy', sname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>





<br />


<% end %>
<%= link_to 'New name', new_sname_path %><br />
 import names from csv  <br />
<%= render :partial => 'snames/import' %>

app/views/snames/new.html.erb
<h1>New sname</h1>

<%= render 'form' %>

<%= link_to 'Back', snames_path %>

app/views/snames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sname.name %>
</p>


<%= link_to 'Edit', edit_sname_path(@sname) %> |
<%= link_to 'Back', snames_path %>